# Generated by Django 5.2.11 on 2026-02-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('material_type', models.CharField(choices=[('book', 'Książka'), ('notes', 'Notatki')], max_length=10)),
                ('condition', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('study_year', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('subject', models.CharField(choices=[('social', 'Psychologia społeczna'), ('cognitive', 'Psychologia poznawcza'), ('general', 'Psychologia ogólna'), ('developmental', 'Psychologia rozwojowa'), ('neuro', 'Neuropsychologia')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
